### ISSUE TITLE
How do I create a Block?

### ISSUE THREAD

**Issue by jeroenVerdonschot** [YMSpektor/dxf-doc#2]
Hi,

Can anyone please explain how I create a block and then insert it?
I added the block to the block table
dxf.addBlock("TEST")

Then I think I have to create a entity.
const lw = new LwPolyline(dxf, some_points, true)

then add the entity to a new block entity
const b = new Block("TEST")
b.addEntities = [lw ] or something ?

at this point I'm lost......

Thanks for your help

Jeroen

**Comment by YMSpektor** [comment]
Hi

This functionality is not fully implemented yet (INSERT entity is not implemented for this moment), but I think you can do it on your own, I can help with it.
1) First you need to create a block like below
const b = dxf.addBlock("TEST");
2) To add entities to the block do
b.entities = [
  new LwPolyline(...),
  // Add more if needed
];
3) To insert block you need to implement an entity class for INSERT (not implemented yet).
export class Insert extends Entity {
  // Implement constructor with needed parameters and writeEntity method
}
Hope these links will help:
https://github.com/YMSpektor/dxf-doc/blob/master/src/entities/ellipse.ts - example of entity class implementation
https://documentation.help/AutoCAD-DXF/WS1a9193826455f5ff18cb41610ec0a2e719-7a04.htm - INSERT entity documentation
4) After that you can just add INSERT entity to the document
dxf.addEntity(new Insert(...));

Please try and let me know in case of additional questions

**Comment by jeroenVerdonschot** [comment]
that worked!

thanks

**Comment by YMSpektor** [comment]
yw :)
